### ISSUE TITLE
error in showing the column number

### ISSUE THREAD

**Issue by ClaudioDaffra** [Genivia/RE-flex#15] opened 2018-12-08 08:46 UTC
I found an error in identifying the exact column number related to some characters : 
key tab is length 4 char.

here is the example source text :

[prova.utf8.txt](https://github.com/Genivia/RE-flex/files/2659506/prova.utf8.txt)

	  1  ç
		@    à
		  ° 	 #
		  ù 	   §
			è 		 +
			* 		^
			  ì 			€
			  æ 		 字
				漢 		 рй
			   אָת
i show you char position

	[1,1]1
	[1,4]ç
	[2,3]@
	[2,8]à
	[3,5]°
	[3,10]#
	[4,4]ù
	[4,11]§
	[5,6]è
	[5,12]+
	[6,5]*
	[6,9]^
	[7,7]ì
	[7,13]€
	[8,6]æ
	[8,12]字
	[9,8]漢
	[9,15]р
	[9,17]й
	[10,6]א
	[10,8]ָ
	[10,10]ת

i expected that  р is 9,13 and й 9,14, but there are other column error, as you can check 
however, i have tried to replace tab with 4 space, but error remains, here second file example 

[x.txt](https://github.com/Genivia/RE-flex/files/2659513/x.txt)

i put here lexer file 

	#include <iostream>
	#include <iomanip>
	#include <clocale>
	#include <ctime>
	#include <cwchar>

	using namespace std;
	%}

	%class{
	%} 

	%option unicode

	%%

	\p{Blank}	{ }
	.       	{ wcout << L"\n[" << lineno() << L","<< columno()+1<< L"]"<< wstr(); } 

	%%

	int main(int argc, char **argv) 
	{
	  std::setlocale(LC_ALL, "en_US.UTF-8");	

	  FILE *fd = stdin;
	  if (argc > 1 && (fd = fopen(argv[1], "r")) == NULL)   exit(EXIT_FAILURE);

	  // crea lexer da stdin o file
	  Lexer lexer(fd);

	  // ci siamo
	  lexer.lex();

	  if (fd != stdin) fclose(fd);

	  wcout << endl ;

	  return 0;
	}

Regards
Claudio

**Comment by genivia-inc** [comment] 2018-12-08 22:20
Thanks for the feedback. Good point. The issue is resolved with version 1.0.10. Documentation is updated to indicate that `columno()` returns the column position taking tab spacing and wide characters into account.

**Closed by genivia-inc** 2018-12-08 22:20 UTC

**Comment by ClaudioDaffra** [comment] 2018-12-09 16:50
I have retested : prova.utf8.txt with spaces  
[prova.utf8.space.txt](https://github.com/Genivia/RE-flex/files/2660749/prova.utf8.space.txt)
  and tabs 
[prova.utf8.tabs.txt](https://github.com/Genivia/RE-flex/files/2660750/prova.utf8.tabs.txt)
but erros remains, 
 
	  wrong      right
	# 3,13       3,12 
	§ 4,17       4,16
	+ 5,21       5,20
	€ 7.28       7,27
	字 8.27       8.26
	р 9,30        9,28
	й 9,32        9,29
	  10,14       10,13 ת 
	  אָ 10,12       10,10 

I have recompiled all with reflex version 1.0.10
can you check please, and consider to reopen, thanks for work you dedicated us.

**Comment by genivia-inc** [comment] 2018-12-09 17:18
Here is the output of 1.0.10 with the updated version for prove.utf8.space.txt, which is correct:

[1,1]1
[1,4]ç
[2,3]@
[2,8]à
[3,5]°
[3,12]#
[4,7]ù
[4,16]§
[5,9]è
[5,20]+
[6,11]*
[6,21]^
[7,13]ì
[7,27]€
[8,15]æ
[8,26]字
[9,17]漢
[9,28]р
[9,29]й
[10,10]א
[10,11]ָ
[10,12]ת

The output for prova.utf8.tabs.txt is also correct:

[1,1]1
[1,4]ç
[2,3]@
[2,8]à
[3,5]°
[3,10]#
[4,11]ù
[4,20]§
[5,13]è
[5,26]+
[6,19]*
[6,33]^
[7,21]ì
[7,41]€
[8,27]æ
[8,42]字
[9,29]漢
[9,42]р
[9,43]й
[10,34]א
[10,35]ָ
[10,36]ת

Perhaps you should reinstall reflex. Make sure that the updated header files are used. If you installed reflex but use a local version of reflex then you will end up mixing both versions with predictable bad results.

- Robert

**Comment by ClaudioDaffra** [comment] 2018-12-09 19:11
all work good.

the problem was in the different setting of the tab editor (4 or 8 spaces)


Il giorno dom 9 dic 2018 alle ore 09:18 Robert van Engelen <
notifications@github.com> ha scritto:
