### ISSUE TITLE
RE/flex generated scanned in a Bison C grammar

### ISSUE THREAD

**Issue by dnicolodi** [Genivia/RE-flex#79] opened 2020-07-26 22:12 UTC
The documentation and the examples suggest that it is possible to use a RE/flex generated scanner in a Bison generated C grammar. However, the header file generated by RE/flex cannot be included into a C source file (at some point down the includes chain `<cstdio>` is included and this does not work in C, there may be other issues as well). AFAICT, in the examples, when the header file generated by RE/flex is included in the Bison sources, they are compiled with a C++ compiler. Unfortunately, because of other constraints I cannot do that. Is the RE/flex generated header file supposed to work in a C source file? Is there an easy way to make it work?

I need the generated header file for the definition of `yylex_init()`, `yylex_destroy()`, `yylex()` and some other functions I define in the RE/flex source file, which are correctly present in the generated header file. But I would also like to be able to use `yyget_text()` and `yyget_leng()`, which do not seem to exist in the header, nor as exported C symbols.

If there is interest in this use case, I can provide a minimal example that demonstrates my issues.

**Comment by genivia-inc** [comment] 2020-07-27 01:29
The scanner requires C++ to enjoy the speed and usability improvements.

Using Bison's generated C code works fine, as long as you compile its source code also with C++, not C because that will never work when including C++ header files such as the one generated by reflex. If your compiler complains about the `.c` extension of the Bison parser source code, then just rename it to `.cpp`. C is a strict subset of C++.

As for `yyget_text()` and `yyget_leng()` they are defined when you set the following options in the lexer specification:
~~~
%option flex
%option reentrant
~~~
This will let reflex generate the scanner with reentrant functions. In fact, these are declared in `include/reflex/flexlexer.h` which is included with option `flex` and the definitions are available with option `reentrant` or `bison-bridge`.

**Comment by dnicolodi** [comment] 2020-07-27 03:04
While C++ being a superset of C may have been true at some point in the past, I don't think that this can be claimed any more: there are plenty of C constructs that are not valid C++. Another issue is symbols mangling in C++. The point I was trying to make is that I don't see why the generated header file needs to depend on any C++ header. At a first glance, the bulk of the work is to replace some macros with `extern "C"` functions. I'll see if I can make this work in my project and I will share the result here.

**Comment by genivia-inc** [comment] 2020-07-27 14:06
ISO C++: "C++ supports every programming technique supported by C95 (C90 plus an Amendment) and earlier."

ANSI C code (C95) and C code up to C99 actually should pose no problems masquerading as C++. I'm pretty sure Bison is C99.

However, there will be changes and additions to the C++ standard as of C++20 that can break C95 code (if certain constructs are used that will be banned).

This seems all a lot of work to me to force things into or from headers to make them compile with C, which I'm not sure is possible given that `--flex` essentially is `-+` in Flex to generate C++ code. Like Flex, RE/flex imports a`flexlexer.h` header file that declares a C++ `FlexLexer` class.

Why not produce C++ code with Bison?

**Comment by dnicolodi** [comment] 2020-07-27 16:42
I am working on a project in which the parser is a small part. If I produce C++ code with Bison, I am only moving the boundary of the problem. I still need to embed some C++ into a C project. Judging from the documentation https://www.genivia.com/doc/reflex/html/#reflex-bison, at some point, being able to use RE/flex generated scanner in a C project was a goal. Indeed, doing it is easy but the RE/flex generated header cannot be used. What I have done is to use this header:
```C
typedef struct _yyextra_t yyextra_t;
typedef void *yyscan_t;

int yylex(YYSTYPE*, YYLTYPE*, yyscan_t, PyObject* builder);
void yylex_init(yyscan_t*);
void yylex_init_extra(yyextra_t*, yyscan_t*);
void yylex_destroy(yyscan_t);

const char* __yyget_text(yyscan_t s);
size_t __yyget_leng(yyscan_t s);

#define yyget_text(s) __yyget_text(s)
#define yyget_leng(s) __yyget_leng(s)
```
where the last lines allow to use `yyget_text()` and `yyget_leng()` from outside the lexer definition. The indirection through the macros allows to keep using the macro version of `yyget_text()` and `yyget_leng()` inside the lexer definition. In the lexer definition I added this code:
```C
%top{
#define YY_EXTERN_C extern "C"
}

...

YY_EXTERN_C const char* __yyget_text(yyscan_t s)
{
    return static_cast<FlexLexer*>(s)->YYText();
}
    

YY_EXTERN_C size_t __yyget_leng(yyscan_t s)
{
    return static_cast<FlexLexer*>(s)->YYLeng();
}
```

**Comment by genivia-inc** [comment] 2020-07-27 17:17
That's nice.

**Comment by dnicolodi** [comment] 2020-07-27 18:17
I think it is an hack that makes the thing work, but I wonder if something could be done to make the RE/flex generated header to work. From this experiment, it seems that some `#ifdef __cplusplus` / `#endif` trickery may solve most of the problems.

Also, can you comment about the use of macros for `yyget_xxx()` functions? Would using functions (that can be invoked from C code) have a noticeable impact on performance? I don't know if the linker is smart enough to inline them. This would solve the remaining problems.

**Comment by genivia-inc** [comment] 2020-07-28 13:23
Because the function definitions are not visible in the Bison parser source (i.e. the function body is lacking), they will not be inlined. This incurs some overhead versus macros or inlined functions. However, it depends on how and when these functions are used in the parser. Note that these two functions `yyget_text` and `yyget_leng` are typically not needed in the parser at all. Lexemes (`yytext` values) are usually returned by the scanner to the parser as the semantic values of tokens (i.e. attributes associated with terminals).

**Comment by dnicolodi** [comment] 2020-07-28 18:38
Absolutely. I need `yyget_text()` and `yyget_leng()` in my application because it has a debug facility that emits the tokens stream along with their semantic value and matched text (lexemes? I never encountered this word before). It is thus not important for these two functions exported to my application to be optimized, it is debugging after all.

**Comment by genivia-inc** [comment] 2020-07-28 19:40
That makes sense. Just saying that a [lexeme](https://en.wikipedia.org/wiki/Lexeme) of a grammar's terminal (token) that represents a [syntactic category](https://en.wikipedia.org/wiki/Syntactic_category) can be passed to the parser as a semantic value. It depends on how the project is structured if this is an easy implementation or not. But for sure it's easier said than done in C.

**Comment by dnicolodi** [comment] 2020-07-28 21:01
I am not sure I understand. As an example, this lexer recognizes dates in the form `YYYY-MM-DD`. These are returned as `DATE` tokens with a `date` object as a semantic value. Running the scanner on the string "2020-07-28" results in a `DATE` token with semantic value `date(2020, 7, 28)` object. The debugging facility prints something like:
```
DATE 1 date(2020, 7, 28) "2020-07-28"
```
where 1 is the line number. Are you saying that one think that could be done is to have a tuple `(date(2020, 7, 28) "2020-07-28")` as semantic value for the token? Because the lexeme is used only in debug, I think that this would be over engineering the solution.

**Comment by genivia-inc** [comment] 2020-07-28 23:56
Semantic values are not atomic, they can be anything, such as a pair or a struct with members. In your case there would be `yylval.text = yytext(); yylval.date = date(yytext);` for example. Typical lexers do more than just return one semantic value. For example, with Bison C++ "complete+location" parsers, scanners return the full location information for each token. That is the starting row/column and ending row/column. Four values plus other semantic values. This is used to enhance syntax error reporting. The parser could have used `yyget_yylineno()`, but that is not the direction in which these technologies are evolving, as with the cleaner Bison complete APIs. On the other hand, there are other ways to share the state of the lexer with the Bison complete parser directly, while ensuring that the state is nicely under control of C++ access privileges. This is efficient too, because accessing the state has zero calling overhead. It is certainly more efficient if the state is rarely used. In that case you don't have to return this state information as semantic values for each token. There are some examples of direct access to the lexer state in the RE/flex examples, such as the Mini C compiler `minic.y`.

**Comment by dnicolodi** [comment] 2020-07-29 04:08
I see. I completely agree and I would implement a better solution if this would not be simply a debug facility. Thank you!

**Comment by genivia-inc** [comment] 2020-07-30 13:32
> I think it is an hack that makes the thing work, but I wonder if something could be done to make the RE/flex generated header to work. From this experiment, it seems that some #ifdef __cplusplus / #endif trickery may solve most of the problems.

Looking into this to improve the `--header-file` output for Bison C use, i.e. when option `bison` or `bison-bridge` is used and the header file is compiled in C.

**Comment by genivia-inc** [comment] 2020-07-30 20:54
The changes to improve reflex are almost done to generate `yyget_text()` and so, for compatibility with Bison-bridge C code with optional use of bison-locations. The C++ parts of the generated header file will be invisible in C, when `lex.yy.h` is included in a C file.

I am keeping the `yyget_func` macros in `flexlexer.h` for C++, which are visible in C++ code to improve efficiency, but will not be visible in C code, obviously.

It is coming together nicely. The C extern linkable functions are:
~~~
    char *yyget_text ( yyscan_t scanner );
    yy_size_t yyget_leng ( yyscan_t scanner );
    FILE *yyget_in ( yyscan_t scanner );
    int yyget_lineno ( yyscan_t scanner );
    YY_EXTRA_TYPE yyget_extra ( yyscan_t scanner );
    int  yyget_debug ( yyscan_t scanner );
    void yyset_debug ( int flag, yyscan_t scanner );
    void yyset_in  ( FILE * in_str , yyscan_t scanner );
    void yyset_lineno ( int line_number , yyscan_t scanner );
    void yyset_extra ( YY_EXTRA_TYPE user_defined , yyscan_t scanner );
~~~
The Bison C examples that come with RE/flex will be updated as well, serving both to demo the toolchain, but also serving as simple unit and regression test cases.

**Comment by dnicolodi** [comment] 2020-07-31 15:22
This is exactly what I was suggesting. Thank you. I am glad that the use case I proposed is not completely unreasonable.

**Comment by genivia-inc** [comment] 2020-08-03 14:58
See update v2.1.3. Several of the Flex+Bison examples, including the bison-bridge examples, are updated to compile with C, not C++. These use the reflex-generated header files. I hope this update works for you too.

**Closed by genivia-inc** 2020-08-03 14:58 UTC
Labels: question

**Comment by dnicolodi** [comment] 2020-08-05 00:08
Thanks. I gave v2.1.3 a try and it works for my use case. Thank you very much.
