### ISSUE TITLE
The documentation for the `\0` escape doesn't match the implementation

### ISSUE THREAD

**Issue by tlemo** [Genivia/RE-flex#216] opened 2024-11-08 03:05 UTC
The documentation says that `\0` matches the NUL character, but at least when using the default matcher, `\0` seems to be treated as the prefix for an octal encoding of a character

**Comment by genivia-inc** [comment] 2024-11-12 13:07
Thank you for your feedback! Will be fixed.

**Comment by genivia-inc** [comment] 2024-11-12 13:26
The problem is actually in the regex converter, which takes the "signature" of a regex engine to make sure it complies and also converts non-supported regex syntax to syntax the the regex engine supports.

Line 53 in `include/reflex/matcher.h` should be updated to add a `0` after the `W` to natively support `\0` escapes:
```cpp
static std::string convert(T regex, convert_flag_type flags = convert_flag::none, bool *multiline = NULL)
{
  return reflex::convert(regex, "imsx#=^:abcdefhijklnrstuvwxzABDHLNQSUW0<>?", flags, multiline);
}
```

**Closed** 2024-11-25 17:35 UTC
Labels: patch, doc
